base_url = "https://micahcantor.com"

description = "Micah Cantor's personal site."

title = "Micah Cantor"

compile_sass = true

build_search_index = false

generate_feed = true

[markdown]
highlight_code = true
highlight_theme = "ayu-mirage"

[extra]
social_media = [
    {name = "GitHub", url = "https://github.com/micahcantor"},
    {name = "LinkedIn", url = "https://linkedin.com/in/micah-cantor"},
    {name= "Twitter", url = "https://twitter.com/micah_cantor"},
]
